cursor #2e2a24
cursor_text_color #a39a8e

foreground            #2e2a24
background            #f4f3ee
selection_foreground  #ffffff
selection_background  #7a3060
url_color             #2e5f96

color0   #1C1A17
color1   #8e173b
color2   #0b7018
color3   #b4aa00
color4   #2a609d
color5   #c6e1ff
color6   #2E5F96
color7   #27282a
color8   #7b7d7f
color9   #c24568
color10  #27a538
color11  #c3b905
color12  #3b73ba
color13  #c6e1ff
color14  #7f9fc3
color15  #dadde1
